### ISSUE TITLE
Hashes are computed incorrectly

### ISSUE THREAD

**Issue by parrilo** [hros/XXhash.jl#2]
Two (related) issues:

1) On v0.7.0, Julia 1.4.1, both Mac and Ubuntu, hashes are clearly incorrect, since we get easy collisions:

    julia> xxh64("a"), xxh64("b")
    (0x8a4127811b21e730, 0x8a4127811b21e730)

For short inputs, it seems as if only the length of the string matters.

2) Also, the test vector in README.md seems wrong. The string "abc" should xxh64 hash to 
0x44bc2cf5ad770999.

**Comment by BioTurboNick** [comment]
Strings of the same length are all producing the same hash value still, in v0.8.0:

```
julia> xxh64("test")
0x382243289186c9d9

julia> xxh64("tesr")
0x382243289186c9d9
```

@hros 

I had strings working in #3, if that helps.

**Comment by BioTurboNick** [comment]
```
xxh32([5,3,'a'])
0x74437f6b
```

This does not match the readme.

**Comment by hros** [comment]
thanks
v0.8.1 which fixes these issues has been registered and should be available shortly
